information:
  name: MLAG_DC2-SW2

vlans:
  - id: 10
    vlan_name: VLAN10

peer_switch_port_channel:
  channel_group: 101
  trunk_group: peertrunk
  description: "PEER SWITCH PORT-CHANNEL"
  mode: active
  members:
    - Ethernet7
    - Ethernet8

peer_switch_svi:
  vlan_id: 4094
  description: "PEER SWITCH SVI"
  ip_address: 10.255.255.6/30
  trunk_group: "{{ peer_switch_port_channel.trunk_group }}"

mlag_configuration:
  local_interface: "{{peer_switch_svi.vlan_id}}"
  peer_address: 10.255.255.5
  peer_link: "{{ peer_switch_port_channel.channel_group }}"
  domain_id: mlag_dc02
  hb_interval: 1500
  reload_delay: 150
  dual_primary_detection: true
  peer_address_hb: 192.168.51.103
  peer_address_hb_vrf: MGMT
  dual_primary_detection_delay: 5
  recovery_delay_mlag: 60

mlag_interfaces:
  - mlag_id: 1
    channel_group_id: 1
    mode: active
    members:
     - Ethernet1
    port_mode: trunk
  - mlag_id: 2
    channel_group_id: 2
    mode: active
    members:
     - Ethernet2
    port_mode: trunk
  - mlag_id: 3
    channel_group_id: 3
    mode: active
    members:
     - Ethernet3
    port_mode: trunk
