information:
  name: NAD-SW2

vlans:
  - id: 10
    vlan_name: Sales

channel_interfaces:
  - channel_group_id: 1
    mode: active
    members:
     - Ethernet1
     - Ethernet2
     - Ethernet3
     - Ethernet4
    port_mode: trunk
    allowed_vlans:
    vlan_id:

Switch_interfaces:
  - interface: Ethernet5
    mode: access
    description: Client Node
    vlan_id: 10
    allowed_vlans: 
